### ISSUE TITLE
Disappearing aspects in research table

### ISSUE THREAD

**Issue by Anguishire** [ArcanaMod/Arcana#5]
![image](https://user-images.githubusercontent.com/79500441/108808206-caac9780-75ae-11eb-867b-6a921ad94b81.png)

If you "hold" aspects with your mouse like shown above (holding 6 precantatio in middle of image), then hit esc, however many aspects you had selected(6) are deleted. I tried this with phial shelves and the phials turned into empty ones.

**Comment by l-Luna** [comment]
Should be fixed.
