### ISSUE TITLE
Label issue

### ISSUE THREAD

**Issue by Anguishire** [ArcanaMod/Arcana#6]
![image](https://user-images.githubusercontent.com/79500441/108933546-ff265f00-7653-11eb-90ed-e038c766b072.png)

Labels placed facing north (i'm looking at them so its south to me) look odd. 

Other directions are perfectly fine -

![image](https://user-images.githubusercontent.com/79500441/108933660-3432b180-7654-11eb-9c1e-a08952368399.png)

**Comment by DcZipPL** [comment]
I forget to close this issue. It was fixed about a month ago.
