### ISSUE TITLE
Workbench phasing out of existence

### ISSUE THREAD

**Issue by Shrosken** [ArcanaMod/Arcana#7]
![Desk Phasing 2](https://user-images.githubusercontent.com/64583521/108974163-0b052780-763a-11eb-9bc2-f26568828fa0.png)
![Desk Phasing](https://user-images.githubusercontent.com/64583521/108974174-0f314500-763a-11eb-849c-6a61ca40a599.png)
These images should explain themselves. I ran the devbuild just base, nothing else and this happened. Not exactly sure what causes this.

**Comment by DcZipPL** [comment]
> Not exactly sure what causes this.

MAGIC

**Comment by AmyMialee** [comment]
Is this still an issue for you? I don't seem to get the same bug.

**Comment by DcZipPL** [comment]
I will close this issue. We can't reproduce this issue. **If someone else has the same problem.**
**Then reopen it again.**
